### ISSUE TITLE
Mana spells for Enchanter

### ISSUE THREAD

**Issue by smashct3** [mixxit/solinia3-core#104]
I believe the Mana spells that are supposed to summon items(such as thicken Mana) are broken.  Unless I'm doing it wrong.  When I try to use the spell it either does nothing or if I spam it all it does is fizzle and destroy my Mana.

**Comment by Silternius** [comment]
The Irony

**Comment by mixxit** [comment]
Trade skills are not implemented or spell reagents do this spell won't work for you

Not on the list of things to work on right now so I'll close this as it's not mana related
