### ISSUE TITLE
Warrior AA missing 

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#108]
Combat fury
Burst of Power
Combat agility
Dauntless Perseverance
Discordant Defiance
Double Riposte
Extended Ingenuity
Ferocity
Finishing blow (i did hear you mention something about this)
Flurry
Hastened -insert skill here- (decreases cooldown on disciplines/skills)
Innate Metabolism (maybe decrease food saturation or something)
Natural Healing
Physical Enhancement
Sturdiness (not to be confused with general sturdiness)
Tactical Mastery
Trials of mata muram (change god name)
Weapon affinity

**Comment by joshuam158** [comment]
Im sorry but you asked and i have 250 points left :')

**Comment by mixxit** [comment]
Jesus thats a list, are any of them cross class?

**Comment by mixxit** [comment]
ill address some of these with the ranger update

**Comment by mixxit** [comment]
going to close this, can you open a ticket per one that is broken else this task remains open forever

i may have also implemented some of these
