### ISSUE TITLE
Levitate/Levitation

### ISSUE THREAD

**Issue by Silternius** [mixxit/solinia3-core#109]
They don't work how they're supposed to. Wizards and casters who can lev are supposed to be able to hover in midair (much like /fly) while you rain down fire and brimstone. Currently, levitate and levitation send you flying into the sky endlessly until you cancel it or shadowstep down, which is extremely dangerous and inconvenient as it means you're often teleporting down to the mobs that you're trying to kill.

Whenever you get the chance, this would be a huge help if I could hover and cast spells

**Comment by mixxit** [comment]
Hey my issue with this is how to do it - the spell currently just uses the levitation potion but if you know of a way to prevent downward motion per frame without having too much effect in the PlayerMoveEvent in all ears

**Comment by mixxit** [comment]
I'm*

**Comment by Silternius** [comment]
Is there a way to mimic the code that enables you to stop falling in /fly for the lev spells? I don't know how it works

**Comment by mixxit** [comment]
not that im aware of without granting fly which this shouldnt give
