### ISSUE TITLE
Community Appreciation!

### ISSUE THREAD

**Issue by AugurOfDoom** [mixxit/solinia3-core#119]
I'd like to give you a 25$ gift card of your choice for what you do. I was informed that you weren't compensated for the work you do on the game. This made me want to show you a token of appreciation from the community. I've already gotten that much enjoyment out of your work and I'd like you to get a little something for all that you've done. Just let me know what you want and an email address to send it to. Or if they don't do email a physical address to have it mailed.

**Comment by mixxit** [comment]
I appreciate the offer but there is no need :) your thanks is more than enough
