### ISSUE TITLE
/lastname not working

### ISSUE THREAD

**Issue by BuffMerman-SheepFiddler** [mixxit/solinia3-core#124]
I can't set a last name even though I made sure it fit all the stated requirements, and others are having the same issue.

**Comment by mikebollandajw** [comment]
Can you please give me a screenshot of it please

Thanks

**Comment by BuffMerman-SheepFiddler** [comment]
![screenshot 129](https://user-images.githubusercontent.com/37271783/38950980-2c175656-4315-11e8-96f3-5ab32a3a35c5.png)
Trying to set a character's name to Drevin Kraig
