### ISSUE TITLE
Necro feedback

### ISSUE THREAD

**Issue by Donaheartstring** [mixxit/solinia3-core#125]
This is what I have found out about the new meta (from what I have been told) about necro The deal is you are supposed to
 summon a pet and let it fight for you after you spell it, but what I have learned is it isnt that simple. 
The pet dies in less that 5 hits and then the caster is next. From my experience as a caster I have found max health didnt
even reach that of my lower level pet. This was at least to say discouraging. The feign death Spell does push aggro onto 
the pet, but when the pet dies you have no time to cast a spell inbetween the pet dying and the mob rushing to your face.
I will look into alternative ways to farm with the necro, but the root rot is now almost impossible to pull off as far 
as I have tried. I will conduct more experiments into the usefullness of the necro spell caster class when it comes to farming
the spells I am using to test at this moment due to lack of a better one is 
Invoke death 
Feign Death
Cascading and devouring darkness
The mob I have tried to test this on is Vengeful specter

**Comment by mixxit** [comment]
pets seem much more sorted now and necros can now charm undead mobs
