### ISSUE TITLE
Passive Mob Spawns

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#132]
Passive creatures (pigs, cows, chickens, sheep, etc) have been spawning more frequently in dungeons. It's beginning to become difficult to target enemies in certain areas, because the animals get in the way. Also, I've begun finding chickens and sheep spawning in strange places all over my home. (like way way way down in stone enclosed basements) Not sure what's up with natural entity spawning, but in dungeons, it definitely seems to be an upcoming issue. Also, just yesterday, every single cow and sheep in my home that I had been breeding despawned. I don't know if these things are related or not.

**Comment by mixxit** [comment]
these are now killable
