### ISSUE TITLE
Sight/Voice Graft Spells

### ISSUE THREAD

**Issue by AugurOfDoom** [mixxit/solinia3-core#134]
Currently don't have any effect.

**Comment by OEillet-Rissa** [comment]
I can currently confirm about Sight Graft (4380).
I will check up on Voice Graft.

**Comment by OEillet-Rissa** [comment]
actually im dumb, these are pet spells, let me test and update.

**Comment by OEillet-Rissa** [comment]
Ok here are my results: 

Voice Graft (4393) I got the message "eXo's Pets head shimmers" but no true effect, I tested talking in local as the spell is supposed to let me speak through the pet from my understanding. No dice.

Sight Graft (4380) I can get 'finish casting' messages though it has no effect whatsoever.

I tested both on a pet of my own and on another players.
