### ISSUE TITLE
Pets not attacking

### ISSUE THREAD

**Issue by Donaheartstring** [mixxit/solinia3-core#135]
When the auto attack update went live my pet will stop attacking due to the "you cannot attack yourself" message I get when casting as well as when I hit the mob I want to die my pet ignores it till I am hit by said mob. I would like clarity from this situation.

**Comment by mixxit** [comment]
hi i just made a level 1 necro to test this and it worked in the case of me hitting a mob and then my pet went after it

i have not seen any you cannot attack yourself messages

it will really help if you can demonstrate this in a video thanks
