### ISSUE TITLE
AA Mastery of the Past

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#140]
This AA needs to be inserted into game for wisdom casters.

Beastlord Cleric Druid Paladin Ranger Shaman

This ability makes it impossible for you to fizzle spells up to a certain level. Rank 1 - level 53. Rank 2 - level 55. Rank 3 - level 57. Rank 4 - level 61. Rank 5 - level 63. Rank 6 - level 65. Rank 7 - level 66. Rank 8 - level 68. Rank 9 - level 70. Rank 10 - level 71. Rank 11 - level 73. Rank 12 - level 75. Rank 13 - 78. Rank 14 - 79. Rank 15 - 80.

**Comment by mixxit** [comment]
Added
