### ISSUE TITLE
Cannot Buff Pets

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#144]
Currently unable to cast buffs on pets unless you are the pet's master. I tried as a paladin to buff another class's pet, and it did not affect it.

**Comment by mixxit** [comment]
which spell did you use

**Comment by Ferreluke** [comment]
Pretty much every paladin spell I used had no effect on pets. (Resolution, Guidance, Bulwark, etc)

**Comment by mixxit** [comment]
Not reproducable right now, reopen when you find a way to prove it

Might have been some previous issue that was fixed?
