### ISSUE TITLE
recently added 'special weapons'

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#147]
recently you mentioned adding 3 special items to tooflus, cinthia and king dramir, after a brief search i checked up on these.

Cinthia has nothing in her lootdrop (CINTHIA2)
King Dramirs blade is named Blood_Point (my assumption is its a life steal blade as you mentioned to me previously) but it has no abilityid attached to it (0)

**Comment by mixxit** [comment]
I believe this was fixed
