### ISSUE TITLE
Tower of Lost Souls Mob Issues

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#150]
With the new targeting system, perhaps the endermite model mobs from this dungeon could be replaced with something a bit more targetable. At level 65, I found it very difficult to deal with them after being chain summoned through walls and across the room by them. (and this place is supposed to be for level 40-50)

**Comment by mixxit** [comment]
Can you provide a nice human looking skull that would fit this mob and i will apply it

**Comment by mixxit** [comment]
fixed
