### ISSUE TITLE
Mez invincibility

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#163]
A report from Aurian_Thornhill

While he/she was fighting in sirens hold they noticed that when mez was cast on them, it also made them untouchable, leading the 'mez will be removed on damage taken' to be nulled and he mentioned being mezzed for 5 minutes straight. 

Invincibility is the issue here, we may need to do another fix session

**Comment by mixxit** [comment]
can you provide a video of this case? difficult to understand what the problem is from the description

**Comment by mixxit** [comment]
this is intentional
