### ISSUE TITLE
Necro Pets Lose Interest In Following Owner And Despawn When You Get Too Far Away

### ISSUE THREAD

**Issue by FalseGameMaster** [mixxit/solinia3-core#164]
I've noticed that while I level my necromancer, my pet is acting weird and isn't following me around all the time and tends to despawn for no apparent reason when I go about 100 or so blocks away from it. I always put the buff, 'Valor' on my pet and myself with my alt account that's a cleric. I don't know if that might have anything to do with it or not.

**Comment by UmbralG** [comment]
To fix this, all you have to do is right click your pet
All summoned pet are patched wolves. They stop following you mainly because owners usually accidentally right click the pet and they obey the command sit like a wolf. 
Hope this fix everything,
Umbra

**Comment by mixxit** [comment]
This has been patched somewhat, the npc will tp to you if they are above 50 blocks now
