### ISSUE TITLE
Summon Set of Items Spells

### ISSUE THREAD

**Issue by UmbralG** [mixxit/solinia3-core#165]
Hello,
Just to let you know, I have wonderful time on the server and I love all the members here. They have been very helpful and fun. I really want to improve the server and my experiences, so allow me to get to the point. The spells that summon sets of items, example: summon phantom leather, do not summon its whole set of items like it's supposed to. The spell I specifically listed only summon a leather boot. I am sure the fix will help lots of new magicians like myself and improve the game experience.
Sincerely,
Umbra

**Comment by mixxit** [comment]
i believe i have the code for this to wrok now, but i will need someone to test before i  implement all the sub items

**Comment by mixxit** [comment]
This has been fixed

**Comment by UmbralG** [comment]
TThank you
