### ISSUE TITLE
infernal cathedral

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#167]
Lacks spell drops

**Comment by mixxit** [comment]
can you list what you want adding in here to what mobs?

**Comment by joshuam158** [comment]
Impure husk: Necromancer/shadowknight lvl60-69 spells
Cleansed_soul: Warrior/Rogue lvl60-69 spells
Wreathed_Cultist: Magician/Wizard lvl60-69 spells
BrandCultist: shaman/druid lvl60-69 spells 
LesserFireGialon: beastlord/ranger lvl60-69 spells
GreatFireGialon: Berserker/enchanter lvl60-69 spells
PureFireAspect: Monk/bard lvl60-69 spells
Ignis_Goop: Cleric/Paladin lvl60-69 spells

**Comment by mixxit** [comment]
fixed by josh
