### ISSUE TITLE
Off-Hand Weapon Procs Not Functioning

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#168]
Was using a Blade of Living Fire on my rogue (level 65/280 Dex/Max skills/Ambidexterity), and it only procs if I'm using it in my main hand.

**Comment by mixxit** [comment]
yep

**Comment by Ferreluke** [comment]
Is this going to be fixed at some point?

**Comment by mixxit** [comment]
I just didn't write the code
