### ISSUE TITLE
Appears off-hand shields don't add stats.

### ISSUE THREAD

**Issue by FallenPig** [mixxit/solinia3-core#17]
Think 1.12.2 changed the id again for offhand like when you updated and had to redo the offhand id to give stats

**Comment by FallenPig** [comment]
Upon further inspection it does work for weapons
https://youtu.be/jIiDPNx6O_8

**Comment by mixxit** [comment]
hi fallen are you saying that weapons grant stats in your offfhand but shields dont?

**Comment by FallenPig** [comment]
Yeah, however the shields now grant all stats besides the resistances like all the magic, fire, ect

**Comment by mixxit** [comment]
Fxied in 91fdcf6
