### ISSUE TITLE
Bandages Disappearing from Reagent Pouch

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#177]
All bandages have disappeared from my characters' reagent pouches. When I put new ones in, they also disappear.

**Comment by mixxit** [comment]
See https://github.com/mixxit/solinia3-core/issues/174

Please confirm this is not working

**Comment by RickStoreGames** [comment]
Can confirm this aint workin

**Comment by mixxit** [comment]
Are you confirming what he is saying that ALL bandages dissapear or just summoned ones

**Comment by RickStoreGames** [comment]
Just the summoned ones are disappearing for me

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/41736753-4fc7e6fe-7585-11e8-871e-00ee14032ece.png)

**Comment by mixxit** [comment]
This doesn't appear broken

Proven through testing:
* Summoned banadages purchased and placed in reagents dont dissapear immediately
* Summoned bandages dissapear on restart just like any other summoned item
* Normal bandages stay in reagents

Closing as i can't find a bug right now

Feel free to reopen if you find a scenario where this isnt the case

Thanks
