### ISSUE TITLE
Pet doesn't do damage

### ISSUE THREAD

**Issue by Fran9676** [mixxit/solinia3-core#179]
I'm trying the enchanter class and I found that the pet of this class doesn't do damage to mobs

**Comment by mixxit** [comment]
This is affecting all pets, thank for reporting this

**Comment by mixxit** [comment]
This is caused by pets having no weapon

**Comment by mixxit** [comment]
Resolved in 06458ab

**Comment by Fran9676** [comment]
it's still bugged

**Comment by mixxit** [comment]
Which pet

**Comment by Fran9676** [comment]
the pet orb doesn't work for my pet

**Comment by mixxit** [comment]
Separate ticket was opened for this
