### ISSUE TITLE
Titles! :3

### ISSUE THREAD

**Issue by Donaheartstring** [mixxit/solinia3-core#18]
Orc Slayer-kill orcs
Beta Tester-help test thingies
Undead Slayer-kill the various undead like zombies and skeletons
Spider slayer- slay the various spiders
Bloodrose Slayer- slay the bloodrose knights
Ogre slayer- slay the ogres
Mushroom Popper- slay the mushroom people of funga
Monster-kill a friendly npc
Truely wicked- go on a killing spree of friendly npcs
Champion-help the people
Hero- help the people to the maximum amount 
List to be continued sorry mixxy had to stop here for rn

**Comment by mixxit** [comment]
implemented!
