### ISSUE TITLE
Morheim Arena Gear issues:

### ISSUE THREAD

**Issue by Dwegin** [mixxit/solinia3-core#191]
I got level 65 shaman gear from the morheim arena, the stats are completely wrong as a mythical piece of it gives a max stat of 20 when this is max level gear. 
![image](https://user-images.githubusercontent.com/36549410/42416325-bd68a9fe-82bf-11e8-937d-6e0cef94557f.png)

**Comment by mixxit** [comment]
please give screenshot of the chestplate
