### ISSUE TITLE
Mezzing makes you fly lol

### ISSUE THREAD

**Issue by FallenPig** [mixxit/solinia3-core#20]
Pretty much explains itself in the youtube vid https://www.youtube.com/watch?v=m0oq5gW86T4
You could let mezzed players move only in -y which would fix this problem. (The video says Counter-strike because my recording software folders flip sometimes and I'm to lazy to change the title.)

**Comment by mixxit** [comment]
love that you posted a video really helps to see what you mean

will look at this tommorow!
