### ISSUE TITLE
spell crits

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#214]
Spell crits for damage spells are not currently working, they say you have crit, but they do no extra damage

**Comment by mixxit** [comment]
I believe you are talking about this message?

`
if (critical) {

				value = value_BaseEffect * ratio / 100;
				
				value += value_BaseEffect*getFocusEffect(FocusEffect.ImprovedDamage, soliniaSpell)/100;
				value += value_BaseEffect*getFocusEffect(FocusEffect.ImprovedDamage2, soliniaSpell)/100;
				value += (int)(value_BaseEffect*getFocusEffect(FocusEffect.FcDamagePctCrit, soliniaSpell)/100)*ratio/100;

				// TODO Vulnerabilities

				// TODO spell dmg level restriction
				// TODO NPC Spell Scale

				if (isPlayer()) {
					getBukkitLivingEntity().sendMessage("* You critical blast for " + value);
				}

				return value;
			}
`
Can you elaborate with some screenshots of non crit and crit damage?

Thanks

**Comment by mixxit** [comment]
i believe this was proven to be working after displaying the critical blast bonus
