### ISSUE TITLE
Agility not providing Armor Class

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#222]
It appears that agility is not granting armor class bonuses. 
"Agility determines how much melee damage enemies inflict. Above 75, the AC provided for each Agility is slight. Below 75 agility causes a large AC hit. For example, on a level 60 ogre SK, going from 76 to 85 AGI provides 3 AC. But going from 66 to 75 AGI provides 45 AC."
At the moment, it seems like AC on even max level characters is quite low. I don't know if this was intentional or something simply overlooked for now.
Level 69 Ranger with high-tier gear for example: https://eq.magelo.com/profile/496399
AC on that character profile is 1220 wearing gear on the cusp of late-game high-tier.

**Comment by mixxit** [comment]
Are you considering the 231 aas the player has spent their direct ac is only 631

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/43853756-eb2da718-9b38-11e8-8b02-b3212e0a7a0d.png)


![image](https://user-images.githubusercontent.com/233287/43853732-de6e7b10-9b38-11e8-802a-bc2a8e51e1c8.png)

**Comment by Ferreluke** [comment]
Either way, that character's base AC is higher than any of our current character's total AC, and agility is giving no direct increase to AC at the moment--making it a useless stat unless; it's performing some hidden benefit. Again, I'm not certain if that's what you intended or something that was overlooked. Was just bringing it to your attention for clarification or adjustment. If we're going by EQ numerical standards, our players are on par with health and stats, but they're still far behind in AC, attack, and mana.

**Comment by mixxit** [comment]
I assure you that agility is a heavily used stat

**Comment by mixxit** [comment]
What is your current AC?

**Comment by Ferreluke** [comment]
For Xander it's just under 500 when fully equipped

**Comment by mixxit** [comment]
See agility on whats its used on: http://everquest.allakhazam.com/wiki/eq:Stats

Here is the formula for defense (please update the wiki)
```
defense = (defenseskill * 400 / 225) + ((8000 * (agility - 40)) / 36000)
```

Here is the formula for mana for non wisdom/int casters
```
maxmana = ((850 * getLevel()) + (85 * agility * getLevel())) / 425
```

Here is the AC modifier for agility
```
if agility is greater than 70
divide agility by 20 and add to AC
apply ac softcap to total ac if final ac formula has exceeded class/level softcap for ac for that player
```

Your AC sounds fine to me and it's definitely not a useless stat

**Comment by Ferreluke** [comment]
Agility is supposed to add an increase to the numerical value for AC, correct?

**Comment by mixxit** [comment]
see above

**Comment by Ferreluke** [comment]
Above says it should. But it is not currently

**Comment by mixxit** [comment]
like i posted above it is applying currently in code, but you may have hit the softcap for ac for your class/level

**Comment by mixxit** [comment]
Proven to work, closing this
