### ISSUE TITLE
Agility to AC Ratio

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#224]
Agility to AC ratio is currently set to 20/1 but may need to be 3/1 according to the stat wiki entry.

https://wiki.project1999.com/Statistics#Agility_.28AGI.29
"Agility determines how much melee damage enemies inflict. Above 75, the AC provided for each Agility is slight. Below 75 agility causes a large AC hit. For example, on a level 60 ogre SK, going from 76 to 85 AGI provides 3 AC. But going from 66 to 75 AGI provides 45 AC."

**Comment by mixxit** [comment]
please confirm this on our test server

**Comment by Ferreluke** [comment]
I believe this issue was resolved
