### ISSUE TITLE
Players are saying they are spawning on the wall of Destin rather than the roof.

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#227]
The wall is outside the chunk we set to spawn so short of barrier blocking it to high heaven I have no idea what to do

**Comment by mixxit** [comment]
Maybe ask khode to try tinkering with this gameRule

spawnRadius | The number of blocks outward from the world spawn coordinates that a  player will spawn in when first joining a server or when dying without a  personal spawnpoint.
-- | --
