### ISSUE TITLE
/edititem bug

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#228]
some base items cannot recieve damage bonuses, such as hoes and pickaxes
see stormwind

**Comment by mixxit** [comment]
Can hoes and pick axes have a damage value in minecraft?

**Comment by mixxit** [comment]
i think this is a resolved, drop the item and pick it back up

**Comment by mixxit** [comment]
Commit patch: c6258ad3694a580ff92e03672a45061d1053b6cf
