### ISSUE TITLE
RP Chat Quality

### ISSUE THREAD

**Issue by Athorgo** [mixxit/solinia3-core#231]
I don't think I brought this up on Github before, but can we PLEASE get our old RP chat back? 

We used to have it to where everyone's name showed up in green in local chat (Red if you were a king back then), then the text surrounding your name [title {name} says: {message} ] The message was also in Yellow. This design was genius in more ways than one. It's clear and it differentiates itself with all the other things that show up in chat. 

Also, please for the love of Methabeht, can the emote (currently ./me) command now show text in the same color as the local chat? In an RP event where a bunch of people are talking (keep in mind we don't even currently have shout and whisper like we used to) the rp quickly turns into a block of text of the same color; most of which might not even relate to your character or current conversation. 

It doesn't have to be exactly the way it was back then, but for too long now (ever since our switch to spiggot as far as I know), our current chat system has remained inferior to what we had before. While I also think there are other things that were debatably done better before on the server, this is one I think everyone that values RP can agree on.

Thanks for reading. Love ya Mixxit.

**Comment by mixxit** [comment]
local chat colour changed to match emote
