### ISSUE TITLE
Reduce Chat Spam/Chat Cleanup

### ISSUE THREAD

**Issue by Athorgo** [mixxit/solinia3-core#232]
This issue refers to anything outside of player input or interaction. I'm talking about the damage you dealt to your target, the "You have not set your personality" message, the [Hints] messages, the You are mezzed, the bard's automatic spells that never stop, the "Foundations Shake" boss kill message. The damage done and taken should be put back where it belongs, above the hot bar, and the bards should have a way to willingly stop casting spells. The rest, please give us the ability to turn them off. 

Yes, even the Personality message; it sends if you are missing any one thing, but maybe people would like to wait, or leave it blank to use later to reflect their character development. Or maybe they just want to ignore it rather than go through the long list of possibilities trying to find something that fits their character the most. 

On top of the poor RP chat features available, and poor color coding, the copious amounts of texts that drag up the chat bar amplifies the previously mentioned issues about the RP chat itself. I believe that cleaning up the chat feed will directly impact the RP experience in a positive way. The RP experience is a value of the server that is paramount to FoE's success. A good dusting and fresh coat of paint is something that I, and I'm sure many others would greatly appreciate. 

Best Regards Mixxit, Athorgo.

**Comment by mixxit** [comment]
I adjusted the personality message yesterday to make it smaller but i didnt change the timer as i thought reminding you once every 30 minutes wasnt so spammy

I can add some filters to the chat messages for sure so ill leave this open while I do the ones you have requested

**Comment by mixxit** [comment]
Breakdown of request to complete for issue:

Task: Move damage you dealt to target back to upper text box (I thought this was already done?)
[ ] Check with athorgo, this seems to not be correct its already in the actionbar
Task: Hide hints
[ ] I'll remove these i don't think they are needed any more
Task: Hide mezzed
[ ] I'll put this in the action bar
Task: Hide bard songs
[ ] I'll make a toggle command for this
Task: Hide personality message
[ ] I'll move this hint to the /who screen so it reminds you whenever you do a /who
Task: Hide foundation shake message
[ ] I'll remove this message, boss deaths are not required
Task: A way to cancel spells
Task: Poor rp chat features
[ ] Check with athorgo what this means in relation to actions needed to be taken
Task: Poor color coding
[ ] Check with athorgo what this means in relation to actions needed to be taken

**Comment by mixxit** [comment]
mez / stun messages moved in commit 0990afc

**Comment by mixxit** [comment]
i think this is everything in this ticket that i can do, please answer remaining questions - ticket will remain open for a few days and be closed if no response
