### ISSUE TITLE
Shadowstep/ Height of Travel Time Problems

### ISSUE THREAD

**Issue by Athorgo** [mixxit/solinia3-core#233]
Can we have ./t spawn back. Why? 

**(EDIT: On second thought, if not ./t spawn, is there a ./n spawn? [Nation spawn] If that sounds more appealing by giving you other things to consider when choosing a nation to join besides just a plot bonus. If that sounds better than ./t spawn, then replace ./t spawn with ./n spawn with the post. I believe both are worth considering.)**

Is it fair that players have to walk so far to get to the dungeons so far out and other towns? Sure I get it that strengths and weaknesses are the intended result of a class system, but the world apart difference between people with Shadowstep and those without is probably one of the most unbalanced points of the game. Say what you will about the various unbalances of combat capabilities of the various classes in the game, but the mobility effects everyone, even people that don't aim to be able to fight, they just wanna travel and RP. They can try to supplement their lack of travel speed with the ultra-rare elytra loot drop, but then again, give an elytra to a shadow-stepper, and they benefit infinity more than anyone without shadowstep, again.

While I would like to suggest more fast travel options, the first thing that I feel should be in the game is ./t spawn, and maybe a ./spawn (that leads to Haven, not Destin). ./t spawn was something we used to always have access to once upon a Fall of an Empire, and we have the GOTC (Great Ocean Trading Company) spell that anyone could summon with a ./spellkit, and lead to somewhere that was either spawn itself, or some central location. GOTC was basically our ./spawn, and so these two teleport abilities were something that EVERYONE had access to. 

So yes, I think we should have ./t spawn and a ./spawn-like capability available to everyone in improve the quality of life of the server. 

**Sorry this one is long.** I understand how you feel about Fast travels being immersion breaking, Mixxit. This is what I feel FoE also needs right now (among other things), and because of the love and passion I have for this server, I want to express my concerns that I have been carefully forming with other members of our community. I want to suggest what I feel to be the best for everyone.

-----------------------------------------------------------------------------------------------------------------
- Food for Thought on Implementation:

Add a timer to these Teleports if you will, add an effect to them whenever you first "caste" them so that anyone they may be role playing with spots it and can react to. Maybe you can even make it so that it can only be casted when you have no roof over your head (like if you're in a dungeon or in a prison). Or somehow make it so that you have to be in the wilderness to use it (so it's like you have to leave the town or dungeon first to use it). 

Also, I'm gonna mention this now, because I know it's going to be a counter argument. New players spawn into Destin and these commands will allow them to get out of the tutorial; to which I say, players can already escape Destin, but just have a reeeally long walk to get to any civilization. Also, the ./t spawn spawn can only be used if you're apart of a town, which can only be the result of someone inviting a new player to their town right as they join the server. Which is something that I and many others do not condone.

**Comment by mixxit** [comment]
No sorry
