### ISSUE TITLE
Rogue Hide

### ISSUE THREAD

**Issue by Fran9676** [mixxit/solinia3-core#239]
Sneak works only for mobs meanwhile you're still visible to players and there isn't any hide passive

**Comment by Ferreluke** [comment]
Disregard this ticket; consolidating rogue issues into one ticket.

**Comment by OEillet-Rissa** [comment]
Rogues should have a Hide ability that allows them to become invisible when standing still (Based on a skill check). Hide + Sneak should allow rogues to move completely invisible at a slow pace (Based on a skill check). If the check fails, they will not appear invisible or the ability may drop at random. I leave it to your genius to figure out how to implement it ^_^
(Copied from the larger ticket, in process of separating them)
