### ISSUE TITLE
Current Rogue Issues

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#240]
Strikes are working properly on mobs but fail to cancel effect on null targets (cows, sheep, etc). I'm not certain if this is an issue that needs to be addressed as it seems to be inconsequential.

Rogue stealth abilities are currently crippled. There seems to be no check for sneak skill vs mobs, and it sometimes fails for reasons unseen by the player. Again, I'm not certain if this is something behind the scenes working properly or if it's actually broken.

Rogues should have a Hide ability that allows them to become invisible when standing still (Based on a skill check). Hide + Sneak should allow rogues to move completely invisible at a slow pace (Based on a skill check). If the check fails, they will not appear invisible or the ability may drop at random. I leave it to your genius to figure out how to implement it ^_^

**Comment by mixxit** [comment]
can these be raised as seperate tickets
