### ISSUE TITLE
Mob Bouncing

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#241]
Some of the npcs in Haven are now bouncing up and down about 2-4 blocks high in one spot. I'm guessing the last patch affecting mob return position resulted in this. I'm not sure if mobs in other places are also doing it, but I'll make mention of it here if I find any others.

**Comment by Ferreluke** [comment]
Also, every npc in Destin is also bouncing.

**Comment by mixxit** [comment]
this was fixed right?
