### ISSUE TITLE
Underpowered Necromancer Pets

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#242]
Currently, the level 65 Necromancer pet (Child of Rarahat) creates a pet with 2820 health. According to the sources I checked, it should have around 4200 health. The 2820 seemed a little low to me, and necromancers have been complaining that their pets die to quickly. Here's the source chart I used for reference: https://strategywiki.org/wiki/EverQuest/Character_classes/Necromancer/Pet

**Comment by Ferreluke** [comment]
The consensus seems to be the same here http://everquest.allakhazam.com/db/spell.html?spell=3314  Also, the pet is supposed to proc lifetap, but after testing clowy111's pet by letting him attack me, lifetap never proc'd.

**Comment by mixxit** [comment]
All pets have been updated
