### ISSUE TITLE
Armor Display Suggestion

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#243]
If it's not too much of a headache to implement, could we have a toggle option to display worn armor items? I really like some of my skins and would like the option to have them seen instead of my armor sometimes. Also, for characters that use invisibility, they'd be able to actually use it without having to remove all their worn armor items.

**Comment by mixxit** [comment]
Hi Ferreluke,

This is technically possible but quite complex 

It requires intercepting the packets for equipment requests

I think the cost of development and potential bugs outweigh the benefit so i will sadly have to decline this request

Sorry mate
