### ISSUE TITLE
Beds Should Heal Players

### ISSUE THREAD

**Issue by tastespurple** [mixxit/solinia3-core#247]
Hello! I am adding this here by request of mixxit from the suggestions-and-polls channel of the Discord server. 

**My suggestion is to enable beds to have the same or similar healing properties as the fountain in Haven.** 

The reason for this suggestion is that:
a) due to bind affinity, beds currently have little use in-game
b) bind wounds only heals up to 50%, and full hunger heals barely anything before it decays.
Therefore, beds that heal would fill the gap between binding wounds 

There are other issues regarding implementation that must be considered, such as:
a) whether or not to replace the healing factor citizens of a town receive for being inside the towny plot with this new feature
b) whether the bed must be owned by the player to receive healing
c) whether the bed must be inside a towny plot to have the effect enabled or 
d) if they are enabled everywhere, whether beds inside a towny plot have special effects like a greater healing factor and
e) whether outsiders can benefit from these effects
f) whether a bed placed in a dungeon or NPC town will have a normal effect
g) any other issue unknown to me.

Personally, I believe that based on the list directly above:
a) Beds should replace ambient healing as realistically beds would be expected in practically all towny plots currently registered in-game.
b) Beds should heal a player regardless of the owner because it supports the creation of things like inns and taverns. Also registering a bed with an owner based on who placed it _may_ require more complicated plugin code with little payoff.
c) I would like beds to heal wherever they are placed, but I think restricting them to towny plots is better for balance. Consider a player who carries around a bed with them and places it on grass whenever they need a bit more health. That is not how the system is meant to be used, yet allowing beds to heal outside of towny plots would surely allow for that kind of abuse.
d) I have no opinion on this. I just thought it might be an interesting issue to explore.
e) I think outsiders should benefit from healing in beds because it supports the creation of things like inns and taverns, especially between cities. Without this kind of implementation, taverns and inns would have no real purpose.
f) I have no real opinion on this but I think it is promising. It could be used as an interesting mechanic in dungeons, but it could also break the experience if misused. 
g) I don't want to pretend like I have a detailed understanding of the project code or even how Minecraft works internally, so there are likely issues I can't anticipate.
However, these are just my opinions on the issues I presented. My only real suggestion is that beds in some way allow the player to heal in a similar fashion to the fountain in Haven.

Thanks!

**Comment by mixxit** [comment]
Hi beds now heal 50 hp and 50 mana per tick (8 seconds)
