### ISSUE TITLE
XP booster ending in 45 mins

### ISSUE THREAD

**Issue by Asercool** [mixxit/solinia3-core#251]
As stated above , XP booster ended in 45mins when it was supposed to in an hour. The XP booster took a while to apply in around 15mins , perhaps that could be the cause of it.

**Comment by Ferreluke** [comment]
I can confirm. It took a lot longer than usual for the boost to kick in and it ended about 15mins before the hour was finished.

**Comment by mixxit** [comment]
Hi this ticket is not clear if it is the XP inspiration boost or the donation based boost

**Comment by Asercool** [comment]
Donation based boost

**Comment by mixxit** [comment]
This is due to the 15 minute time to transfer over, i have modified it to increase the duration period to 15+ minutes, should do the job
