### ISSUE TITLE
Charm Spells Progress

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#257]
When charm breaks, the former pet cannot be controlled, however, it does not agro and cannot be damaged.

During a fight, the pet and the creature targeted both get about 200 hp regen and all fights become a never ending stalemate.

During the stalemate fight, the target of my pet loses its regen if I assist the pet, however, the pet still remains basically invincible.

The lowest level charm spell is capable of charming max level pets far beyond the intended level cap range of the spell.

**Comment by mixxit** [comment]
I believe most of this is fixed except the levels bit, please confirm

**Comment by mixxit** [comment]
added resist checks, i believe this is all done now
