### ISSUE TITLE
Fizzles Occur at End Instead of Beginning of Spell Cast

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#258]
Fizzles should be occurring during the beginning of a spell cast rather than at the end. Currently, you can spend the full cast time of a 10sec spell and not see the fizzle result until the end. Spell fizzles should occur during the first second of casting.

**Comment by mixxit** [comment]
I don't believe this is correct please check project 1999

**Comment by Ferreluke** [comment]
It worked that way just the other day as we were playing on the emu.

**Comment by mixxit** [comment]
see if you can find anything on Fizzle Time for spells

**Comment by Ferreluke** [comment]
Video demonstrating fizzles occurring at the beginning rather than at the end of spell casting. https://www.youtube.com/watch?v=onK_iDcTNE4
