### ISSUE TITLE
Necromancer pet check

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#259]
Lucian/Cthulu attempted to summon child of rarahat via the special item given to him and it did not work. Followed by the attempt with the actual spell which also failed to bring in a pet

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/50059349-968eee00-017d-11e9-9e98-382da35f3c25.png)

I just tried with the spell, told me i needed reagents so i added bone chips to my reagent pouch and it spawned fine

Why is a level 65 pet being added to an item? Isnt that really OP?
