### ISSUE TITLE
Clicking to fast voids new shield mechanic.

### ISSUE THREAD

**Issue by FallenPig** [mixxit/solinia3-core#26]
In the video you can see that when I click fast everytime it registers a hit (at the soonest availability) the damage does 100% instead of 85% of the damage, I don't have a video from where I was being hit by mobs but a group of the same mob will re-create this and deal 100% damage instead. https://youtu.be/snyNGT8d2Q4

**Comment by mixxit** [comment]
Negated shield effects right now for the new account system

**Comment by mixxit** [comment]
Ac
