### ISSUE TITLE
Weapon check coding

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#260]
I believe some spells need to have a code written in to check for current weapons wielded to cast them such as whirlwind blade

**Comment by mixxit** [comment]
is this a specific type of weapon or something like an axe throw reagent? is it supposed to consume the weapon? etc

cheers

**Comment by joshuam158** [comment]
Player based AoE, warrior spell. Last time we spoke about this you mentioned that it needed to be able to read the weapon you are using, to determine its damage. There is no reagent/consumable item

**Comment by mixxit** [comment]
This has been implemented, it is missing some shield bonus checks

Thanks
