### ISSUE TITLE
Child of Rarahat

### ISSUE THREAD

**Issue by Clowy111** [mixxit/solinia3-core#261]
Says I successfully summoned my pet, but only shows up around 2/10 times

**Comment by joshuam158** [comment]
oh damn you to. mix said he tested it and it was working fine, guess he got lucky

**Comment by mixxit** [comment]
please confirm this is just this pet

**Comment by mixxit** [comment]
Worked 10/10 times

![image](https://user-images.githubusercontent.com/233287/50087798-16a66980-01f9-11e9-9eb8-31c561f361d5.png)

Closed, prove me wrong
