### ISSUE TITLE
Illusion bug

### ISSUE THREAD

**Issue by Silternius** [mixxit/solinia3-core#264]
Mask covers entire screen, not letting you see anything while disguised in first person mode. In second and third person modes, the movement for the illusion is about a second behind your actual movement.

**Comment by Ferreluke** [comment]
This is a known issue, and an in-game fix has been placed in the form of a command. The command appears anytime you use any sort of illusion/disguise, and it allows you to toggle it off in your view. (others will still only see you as the illusion/disguise)

**Comment by Silternius** [comment]
Ah, then that's probably the best that can be done.
