### ISSUE TITLE
Levitate/Levitation

### ISSUE THREAD

**Issue by Silternius** [mixxit/solinia3-core#266]
They don't work how they're supposed to. Wizards and casters who can lev are supposed to be able to hover in midair (much like /fly) while you rain down fire and brimstone. Currently, levitate and levitation send you flying into the sky endlessly until you cancel it or shadowstep down, which is extremely dangerous and inconvenient as it means you're often teleporting down to the mobs that you're trying to kill.

Whenever you get the chance, this would be a huge help if I could hover and cast spells.

UPDATE: Bryson has tested this on EQ and has figured out exactly how it's supposed to work and how to implement this with MC mechanics.

**Comment by Silternius** [comment]
I believe it has something to do with the levitation effect on 255, and it's supposed to keep you a limited distance from the ground.

**Comment by mixxit** [comment]
test it with /effect and we can do this

**Comment by Silternius** [comment]
I don't have access to /effect, but Bryson just tested it and it works. Levitation on 255 that is.

**Comment by Ulthirm** [comment]
https://www.youtube.com/watch?v=xtwOLcg-RhA&feature=youtu.be    I thought I had shown you prior, sorry.
