### ISSUE TITLE
Crippling Blow

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#269]
Innate warrior ability that i haven't seen/heard of: Crippling blow. Chance on crit to double the damage and stun for a short duration

Reference: https://forums.daybreakgames.com/eq/index.php?threads/what-is-crippling-blow.199416/

**Comment by mixxit** [comment]
Requires implemention for effects:

IncreaseSpellHaste
~~AttackSpeed~~ Added
LimitCombatSkills
~~CurrentHP~~ Added
