### ISSUE TITLE
Shields block 15% of damage and not 85%

### ISSUE THREAD

**Issue by FallenPig** [mixxit/solinia3-core#27]
I noticed when against Zombie_Noble they would hit me for about 2-3 hearts every hit depending on what count my hp was at, but then I would block and I would end up taking 1 1/2-2 hearts per hit with 1 1/2 being only when I'm something like 5hp away from losing the next half heart. Maybe its not 15% its blocking and it's more, but whichever it is it's certainly much more than 15% of damage getting through.

**Comment by mixxit** [comment]
Intentional
