### ISSUE TITLE
Rogue Sneak

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#273]
Rogue stealth abilities are currently crippled. There seems to be no check for sneak skill vs mobs, and it sometimes fails for reasons unseen by the player. Again, I'm not certain if this is something behind the scenes working properly or if it's actually broken.

**Comment by mixxit** [comment]
please issue #239

**Comment by mixxit** [comment]
woops didn't realise that you had seperated the issues
