### ISSUE TITLE
Strikes against null targets

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#274]
Strikes are working properly on mobs but fail to cancel effect on null targets (cows, sheep, etc). I'm not certain if this is an issue that needs to be addressed as it seems to be inconsequential.

**Comment by mixxit** [comment]
Is Strike a spell or do you mean melee attack

Can you post the spell id?

**Comment by OEillet-Rissa** [comment]
This is believed to be fixed.
