### ISSUE TITLE
Berserker throwing axes

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#284]
Berserker's throwing axes on a single cast gives 20 axes that is a single-use and non-stackable. It difficult to use throwing axes at its current moment as you still need to drag them manually from the inventory slot to the hotbar to use them. Not to mention they take up 20 of 36 inventory+hotbar slots.

**Comment by Ferreluke** [comment]
Need exact spell name

**Comment by OEillet-Rissa** [comment]
I believe it happens with every summonitem spell for Berserkers. I just did it with Blunt_axe (80886). and my inventory is now full of axes.
![2019-01-04_00 49 03](https://user-images.githubusercontent.com/41124568/50675220-a5b5ce80-0fba-11e9-9464-ffafeaf992e9.png)

**Comment by Ferreluke** [comment]
Okies, I have an easy fix in mind for this

**Comment by OEillet-Rissa** [comment]
Sounds good, I think the original question was simply if they could be made stackable. But im sure any fix you have in mind will work beautifully.

**Comment by Ferreluke** [comment]
This has been completed
