### ISSUE TITLE
Berserker Innate Ability

### ISSUE THREAD

**Issue by Asercool** [mixxit/solinia3-core#285]
Berserker Innate ability is currently not added in even though the class description said so.

Cited from EQ website.
berserkers develop the ability to go into a controlled frenzy at level 6. Frenzy is usable every 12 seconds (quicker if you have a haste item or haste spell on you) and is effectively 3 extra swings at your opponent.

**Comment by mixxit** [comment]
This can be high priority as I need frenzy for mobs
