### ISSUE TITLE
Books

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#291]
Can we please kill those things? The ones that pop in new characters inventories? They are a bit outdated and lead to some confusion since there’s now Destin. Players keep trying to find Dugul McMan and get frustrated because the book directs them to him, and he’s in Haven. 😄

**Comment by Ferreluke** [comment]
The books were removed from game just yesterday.

**Comment by OEillet-Rissa** [comment]
Huh, sorry, saw someone else talking about then. Didnt see that happen!
