### ISSUE TITLE
Broken Mez Ability

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#295]
Currently Mez functions as an everlasting stun rather than a mez, which should break as soon as the target receives damage. All mez spells are affecting creatures beyond the spell's level range, and some mez spells (such as Pixie Strike) are currently irresistible. This was never a huge issue before, but as more and more players are using and abusing this ability, it is quickly causing unfair conflicts among players.

**Comment by mixxit** [comment]
im going to close this as this is too many issues in one ticket

for example it says mez spells are affecting creatures beyond the spells level range

can you please confirm each issue and raise them as seperate bugs as i dont know whats already fixed and not fixed

thanks
