### ISSUE TITLE
Magician Spells

### ISSUE THREAD

**Issue by RoweFrost** [mixxit/solinia3-core#297]
Hello! This issue is not super important, as these spells are not essential. I just wanted to let you know about them. The following spells do no Summon anything
Summon Crystal Belt
Summon Fireblade
Summon Sphere of Air
Summon Dagger of the Deep
Dimensional Hole
Girdle of Magi'Kot
Summon Jewelry Bag

These spells display and error along the lines of ERROR-ADMIN-ALERT when tried to cast.
Imbue Fire
Imbue Storm

Thank you!

**Comment by OEillet-Rissa** [comment]
I am splitting these up to be their own issues.
