### ISSUE TITLE
Summon Crystal Ball

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#298]
Spell does not summon anything

**Comment by mixxit** [comment]
content team can fix these

**Comment by Ferreluke** [comment]
Need exact spell name

**Comment by OEillet-Rissa** [comment]
Spell: Summon Crystal Ball (9980)

**Comment by Ferreluke** [comment]
Ah, it's Crystal Belt

**Comment by Ferreluke** [comment]
This has been completed
