### ISSUE TITLE
Lay On Hands unbalanced 

### ISSUE THREAD

**Issue by Athorgo** [mixxit/solinia3-core#30]
The Lay on Hands spell, spell exclusively for paladins and available at level 1 is unbalanced I believe. It costs 30 mana to caste and I've yet to see it fail to heal anyone to full health, no matter how much health they're missing. I almost would go as far to say that it's set to heal to full health, period. I bring this up because it doesn't seem intended to be this strong.

**Comment by mixxit** [comment]
Updated to use recast timers
