### ISSUE TITLE
TemporaryPets spell effect types

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#319]
Spell currently produces no effect.

**Comment by mixxit** [comment]
I think this is the item ID not spell ID

**Comment by mixxit** [comment]
- [1]TemporaryPets: BASE: 1 Formula: 100 Max: 18
- targettype: 5(Target) teleport_zone: RagingServant

Should read from teleport_zone to spawn Base amount of pets to attack target until death and then despawn

Not currently supported, requires tracking of multiple uncontrollable pets at once

**Comment by mixxit** [comment]
Example spell ID: 8037
