### ISSUE TITLE
New "seat" pluggin effects mez spell

### ISSUE THREAD

**Issue by FallenPig** [mixxit/solinia3-core#32]
When a player is sat on stairs and they become mezzed they are able to freely move their view

https://www.youtube.com/watch?v=PurLaIHPBQM

**Comment by mixxit** [comment]
Does the same thing happen if crouched and mezzed?

**Comment by FallenPig** [comment]
Mezzed Athorgo (made sure he was already crouched when I first mezzed him as well) and the only thing he could do was crouch.

**Comment by mixxit** [comment]
put this on low priority for now
