### ISSUE TITLE
Mastery of the Past Not Working

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#320]
Mastery of the Past is currently not preventing fizzles from spells below the level range it should provide.

**Comment by mixxit** [comment]
Are you saying the lower tiers are broken or all tiers are broken

**Comment by mixxit** [comment]
Like is it just the new tiers we've added that are not working

**Comment by Ferreluke** [comment]
All tiers. I fizzle level 58 spells still

**Comment by mixxit** [comment]
Proven to work on level 58 spells
