### ISSUE TITLE
Proc Research Results

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#321]
From all sources I've found, procs should not register on ripostes and riposte should only occur on main hand
https://everquest.wikia.com/wiki/Riposte
https://forums.daybreakgames.com/eq/index.php?threads/curious-about-riposte.200439/

On weapon procs:
Weapon Proc Rates
http://everquest.allakhazam.com/wiki/eq:Proc (~Live, sounds right)
http://www.thesteelwarrior.org/forum/showthread.php?t=13613
Proc rates are computed on a procs per minute basis. I believe this is the same number for the vast majority of weapons, but some weapons have a higher adjusted procs per minute rate, and some such (with big procs) are adjusted downwards. The game translates the weapons targeted procs per minute and applies it to your weapon. If you are swinging 100 times a minute with your main hand, and the targeted procs per minute is 5, then the game essentially makes this computation:

5 procs divided by 100 swings = chance to proc per swing
5 / 100 = 0.05 or 1 in twenty chance.
Now if your haste wears off, and you're only swinging 50 times per minute, the game actually will up your chance to proc per swing

5 / 50 = 0.10 or 1 in 10 chance to proc per swing
This is confusing to some people but it's definitely true.

The rough formula is (DEX/170) + 0.5 = proc per minute rate for main hand, and offhand is half that rate.
Source: https://wiki.project1999.com/Game_Mechanics#Weapon_Proc_Rates

A "proc" in EQ is an effect on a weapon that has the chance to randomly go off in combat.

Proc rates are independent of delay; a high delay weapon procs just as much as a lower delay weapon (generally speaking.) Some weapons do have 'procmods' that effect the proc rate in one direction or another; an example of this is Bloodfrenzy.

The base proc rate for a 305 dex level 65 person is 2 procs a minute; with 5 WA this increases to 3 PPM, with 5 WA and 100 CE this increases to 4 PPM.
source: http://everquest.allakhazam.com/wiki/eq:Proc

However, I've found no conclusive data on whether procs should occur on double attacks. In fact, I can't even find mention of procs on double attack.

**Comment by mixxit** [comment]
This has now been fixed, thanks!

New formula is here https://docs.google.com/spreadsheets/d/1AaiGIjr35uFY4kT8peP8BoiCEYkSc9Pe_VasNWsFBF4/edit?usp=sharing
