### ISSUE TITLE
Backstab Enhancement

### ISSUE THREAD

**Issue by Asercool** [mixxit/solinia3-core#322]
Backstab can only be used while in melee range and facing one's target.

If a rogue uses Backstab on the frontal arc of the target body, the Backstab skill will automatically "fail" with a message telling the rogue to get behind the target.

If a rogue uses Backstab on the rear arc of the target's body, an actual Backstab attempt will be executed, resulting in a melee swing that deals tremendously amplified damage if it hits.

**Comment by OEillet-Rissa** [comment]
Leave these issues in Suggestions and Polls channel, not here.
