### ISSUE TITLE
Backstab

### ISSUE THREAD

**Issue by Asercool** [mixxit/solinia3-core#323]
Double , Triple , Quad backstabs chance

**Comment by OEillet-Rissa** [comment]
What are you asking for???

**Comment by mixxit** [comment]
https://everquest.wikia.com/wiki/Backstab

**Comment by mixxit** [comment]
on hold as this is a skill and skills are kinda difficult to implement

**Comment by OEillet-Rissa** [comment]
Leave these issues in Suggestions and Polls channel, not here.
