### ISSUE TITLE
Spell Crits Are Not Working Properly

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#327]
This AA is supposed to function as follows:
This ability gives you a chance to land critical hits with your direct damage spells and increases the damage you do when you land critical hits. The ability levels increase your chance to sore a critical by 2, 4, and 7 percent and increase the damage dealt by critical hits by 40, 60 and 100 percent
It appears the values are reversed. Critical chance is 40, 60, and 100 percent and crit damage is increased by 2, 4, and 7 percent. Casters desperately need this one resolved.

**Comment by joshuam158** [comment]
Casters are in the shit currently, might be worth a try

**Comment by mixxit** [comment]
liar liar pants on fire, description was just wrong - confirmed in EQEmu

added destructive fury aa which is actually a spell crit AA
