### ISSUE TITLE
Pets miss attacks far too often

### ISSUE THREAD

**Issue by FallenPig** [mixxit/solinia3-core#33]
Not sure if they miss 100% of the time but he couldn't manage to hit a lvl 16 goblin as a level 34 summon
https://www.youtube.com/watch?v=CuFJ-u1MSgE
EDIT: I made sure to hit the goblin with Gravity Flux leaving him at 20> hp and my pet couldn't deal that damage even with having their damage set at 40

**Comment by mixxit** [comment]
i havent forgotten about this i will get back to it soon

**Comment by mixxit** [comment]
are pets better now they have a race and class?

**Comment by mixxit** [comment]
Closing this since no response
