### ISSUE TITLE
Minimum level?

### ISSUE THREAD

**Issue by Lemondrop1999** [mixxit/solinia3-core#332]
Hi I realized these wings don't come with a minimum level, and was wondering if they should? 

![image](https://user-images.githubusercontent.com/46408556/50798555-9de17d00-128d-11e9-9aad-52906a4acb55.png)

thanks :)

**Comment by mixxit** [comment]
someone can fix this for you :-)

**Comment by Ferreluke** [comment]
This issue has been resolved
