### ISSUE TITLE
waist slot

### ISSUE THREAD

**Issue by Fran9676** [mixxit/solinia3-core#334]
waist slot is actually bugged, I equipped a waist item got trough inspiration, but the actual slot has the hands item slot and by clicking "click here to remove" the waist item you can duplicate the item that is in the hands slot
![2019-01-09_16 46 13](https://user-images.githubusercontent.com/40521706/50910583-64944300-142e-11e9-8421-fff9cf173630.png)

**Comment by mixxit** [comment]
Fixed in 60a2f3e
