### ISSUE TITLE
Destroyer's Volley (berserker spell)

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#342]
This spell may not currently work, however when targetted at a mob (not player) and casted, it spams infinitely until riposted.

**Comment by mixxit** [comment]
its currently doing that or is supposed to do that?

**Comment by joshuam158** [comment]
Its currently doing that, it is supposed to throw 4 axes seperately, with a 10000% accuracy mod. Instead it gets stuck just throwing axes non stop until you are hit. Although the spell does no damage, Dernable can confirm that this is annoying af
