### ISSUE TITLE
Can staff remove vampirism from OOC bites?

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#347]
It has become more and more prevalent with out of character biting and forcing vampirism onto characters that kind of puts a lot of confusion on roleplay and can make events sketchy.  I was hoping staff could remove vampirism from people who get bitten OOC without permission, not to simply remove it from the people who have been vampires all along or asked/ agreed to it.

**Comment by mixxit** [comment]
added /removevampirism <mcname>
