### ISSUE TITLE
Unarmed Damage Bug

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#361]
Players are reporting the ability to hit for 500-1000 damage when hitting with no weapon equipped. I tested with a level 70 unarmed, unbuffed enchanter and hit for 560 damage against level 65 creatures.

**Comment by mixxit** [comment]
Provide context for debugging

Target mob name
Attacking class 
Attacking class stats

**Comment by mixxit** [comment]
Also skill levels

**Comment by mixxit** [comment]
this has been open for 3 weeks but no information provided yet
