### ISSUE TITLE
Stamina AA increase not granting additional health

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#363]
When buying the stamina AA, it is not granting extra health. It was working until I bought full ranks in Planar Power. I don't know if that has anything to do with it, but the issue was first brought to my attention by another player.

**Comment by mixxit** [comment]
Please provide debug information of

/debugger SoliniaLivingEntity getStamina Dernable  (or whatever your minecraft username is for testing)

**Comment by mixxit** [comment]
Hey dern,

Did you do above or did we fix it> Im not sure, this is open either way :-)
