### ISSUE TITLE
Fire Rune not working

### ISSUE THREAD

**Issue by Silternius** [mixxit/solinia3-core#364]
Fire Rune seems to be broken. When used it gives the right spell message, but gives no effect in /effects, nor seems to increase any stats or rune values.

**Comment by mixxit** [comment]
- [1]PersistentEffect: BASE: 1 FORMULA: 100 Max: 0

**Comment by mixxit** [comment]
targettype: 6(Self) teleport_zone: IOFireRuneTrap

**Comment by mixxit** [comment]
spellaffectindex: 4 (Summon)

**Comment by mixxit** [comment]
PersistEffect spell effect types are not currently supported, added to low priority queue
