### ISSUE TITLE
Waist Item broken?

### ISSUE THREAD

**Issue by Lemondrop1999** [mixxit/solinia3-core#366]
It appears my waist slot item isn't working as it should be? Any stats it grants don't seem to work when equipped (but they do show up if held in hand)
Said item:
![image](https://user-images.githubusercontent.com/46408556/53604656-f5071e00-3b69-11e9-95b1-a3a0a183e7ce.png)

Stats when in hand:
![image](https://user-images.githubusercontent.com/46408556/53604682-0b14de80-3b6a-11e9-8204-ccaf04f8addf.png)

Stats when equipped:
![image](https://user-images.githubusercontent.com/46408556/53604714-25e75300-3b6a-11e9-854b-eedf93db3663.png)

**Comment by mixxit** [comment]
Interestingly both screenshots show the same amount of STA
