### ISSUE TITLE
Summon Warder spell does nothing

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#371]
Summon Warder spell (4685) 

Emits a particle effect but does not actually summon a pet like it’s supposed to. Also doesn’t withdraw mana.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mixxit** [comment]
Spell ID is 2632

**Comment by mixxit** [comment]
This is missing the npc definition for BLBasePet

**Comment by mixxit** [comment]
On hold pending lookup the eqemu values for BLBasePet
