### ISSUE TITLE
Add invisible check to GlowAPI call

### ISSUE THREAD

**Issue by Ulthirm** [mixxit/solinia3-core#372]
Check for invisible effect when calling for GlowAPI using bukkit's getActivePotionEffects or similar so that invisible players cannot be viewed using this method . (As a sidenote, this might also be an effective method of implementing see invisible using a unused color of glowing if it can be used to only be viewed by caster similar to how targetting is)

**Comment by mixxit** [comment]
I dont think this is a bug as you can target invis players in EQ with /target

* i think * - can someone test?
