### ISSUE TITLE
Limited characters for a name in the Character creation menu

### ISSUE THREAD

**Issue by Ipponvader** [mixxit/solinia3-core#376]
I don't know if it is intended or not but if you want to create a character with the character creation menu of the mod you can only use 7 characters for the first and last name. if you try to type more it doesn't fit. I hope that this can be changed to a higher amount, something like 9/10 if possible.

**Comment by mixxit** [comment]
hi this is due to minecraft nameplate restrictions of 15 characters sorry matey
