### ISSUE TITLE
Purchased Mob Eggs Have No AI

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#378]
The animals (horse, chicken, pig, etc) purchased from vendors are unable to move once spawned. They seem to be rooted to whatever block they're spawned upon unless pushed by a player. As a result, they're unable to be bred. We tested this vs animals spawned from normal spawn eggs, and the normal ones are able to move and breed. I don't know if this was intentional or some weird quirk that's resulting from the mobs that spawn from the new vendor-sold spawn eggs.

**Comment by mixxit** [comment]
this might be due to the way i made the world use only solinia mobs (which is why we dont have any natural spawns)

id need to look a bit more into this to maybe make some exceptions for creatures that are not monsters

**Comment by mixxit** [comment]
so i just went to the vendor and bought some of these eggs and the npc spawned from it (Sheep) walked around happily with AI

**Comment by Ferreluke** [comment]
Issue resolved by Mixxit
