### ISSUE TITLE
You can resist your own self-casted buff spells

### ISSUE THREAD

**Issue by FallenPig** [mixxit/solinia3-core#38]
I'm using alliance but it could be a large problem for healing classes who don't have their highest heal spell and other classes that can buff, removing resistance to buff spells for players in group and self would be useful. 
![alliance](https://user-images.githubusercontent.com/32177385/32528000-80b7de06-c3e5-11e7-86d6-74b7590560bd.PNG)

**Comment by mixxit** [comment]
Hi Fallen,

This is an odd one was we have a check

if (soliniaSpell.isResistable() && !soliniaSpell.isBeneficial())

Do you have the spell in question?

**Comment by FallenPig** [comment]
I'm not at my pc but it was the Alliance spell that had +Faction for enchanter level 8, perhaps +Faction is not seen as a buff/is not active as a buff yet?

**Comment by mixxit** [comment]
Faction doesnt do anything right now so I can imagine it would resist anyway

If there is another spell example reopen this ticket ok?
