### ISSUE TITLE
Sunta gear issues

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#384]
Sunta has given players the wrong weapons

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mixxit** [comment]
which

**Comment by OEillet-Rissa** [comment]
>which

@mixxit I saw people saying they are meant to have staffs (crushing) but recieved swords

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OEillet-Rissa** [comment]
I think it may be actually a confusion because /claims isn’t character specific so when I went to claim as my cleric after testing as warrior I had swords and got confused for a moment before I saw my staffs

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
