### ISSUE TITLE
Sunta gear issues pt.2

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#385]
Sunta has given a few people incomplete sets of gear

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mixxit** [comment]
do you know who

**Comment by riroo** [comment]
My alt account, SubpotentFrog32 on character Therin_Raylegh only received a chest plate, leggings, and 2 weapons of the season. I know the items were not received by another character as he received a few items of the season so it appears he was only given a select few seasonal items.

**Comment by mixxit** [comment]
what is your alts class

please can you send a picture of his /claims list

**Comment by riroo** [comment]
![Solina](https://user-images.githubusercontent.com/59296875/71535380-ea6d0080-28c2-11ea-8722-addefe7a27e3.PNG)
It was a level 9 shadowknight at the time of completing the event.
