### ISSUE TITLE
New Player Mod problems

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#391]
New players may be having trouble with our mod, maybe we can make it so they can talk but not move without it in case they need assistance? Or have our "Your lacking the right version" message give a link and say to go here for the mod? I believe this confusion could be a big loss of new players

**Comment by mixxit** [comment]
Hi RIssa,

It is a lot of work to allow them to talk with no race so I havent been able to fully implement this but most of it

Thanks

**Comment by OEillet-Rissa** [comment]
Thank you!! It was just a thought to try and make it easy!

**Comment by mixxit** [comment]
Hi Rissa,

Players who dont have the mod or set race can now fully talk in /ooc

Thanks
