### ISSUE TITLE
Problem compability and  conflict

### ISSUE THREAD

**Issue by Miyazaki1992** [mixxit/solinia3-core#4]
Actually the plugins need call essetial but essential are dead plugins and cant work with my other plugins because he create conflict money and other,  can you add choose citizen or essential in the  config of your plugins ?

**Comment by mixxit** [comment]
Can you confirm that you use Vault for your economy with whatever other plugin? I can support that instead

**Comment by mixxit** [comment]
Removed essentials dependency
