### ISSUE TITLE
/unstuck command

### ISSUE THREAD

**Issue by OEillet-Rissa** [mixxit/solinia3-core#400]
Gives staff coords of stuck location as well as player username, maybe even scoots them to the succor?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mixxit** [comment]
will this be abused to escape dangerous situations?

**Comment by riroo** [comment]
Yes, perhaps make it cost money/not work in dungeons/only be usable on a time limit?

**Comment by mixxit** [comment]
fixed in commit 5158c1501d197082e8c9a2e09afb3841a835124c
