### ISSUE TITLE
Voting Sites Not Rewarding Inspiration Points

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#401]
The following sites aren't registering inspiration points for votes:
https://minecraftlist.org/vote/5962
https://minecraftservers.org/vote/464284
https://www.minecraft-servers-list.org/index.php?a=in&u=mixxit

**Comment by mixxit** [comment]
I voted on minecraft list and it was successful
![image](https://user-images.githubusercontent.com/233287/71627915-41d5de00-2bed-11ea-8914-2df03dd78de2.png)

I voted on MinecraftServers.org and it failed
![image](https://user-images.githubusercontent.com/233287/71627931-5dd97f80-2bed-11ea-83af-d19ef38c5038.png)

the key has been updated so this should be ok now

I voted on minecraft-servers-list.org and it failed

Its key was already fine but i have updated the key anyway
