### ISSUE TITLE
All Languages Spoken By Players Are Understood Without Language Skills

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#402]
Even without possessing the skill for a specific language, players can understand the language being spoken by any other players (similar to how admins understand all languages). Tested this with several players while speaking both current racial languages and legacy race languages.

**Comment by Ferreluke** [comment]
Upon further investigation, it seems this only applies to staff characters. Any admin account character can be understood by anyone no matter what language the admin account is using.

**Comment by mixxit** [comment]
Yep that's intended so we can help people

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Ferreluke** [comment]
Okies, just making sure. Thanks, I'll close this issue.
