### ISSUE TITLE
Damage tip on bottom of screen false numbers

### ISSUE THREAD

**Issue by Ulthirm** [mixxit/solinia3-core#426]
Well myself, however the tooltip on the bottom of the screen will sometimes state a negative number despite the entity in mention not dying. 

To replicate:
Spawn NPCID:  1252
Summon ItemID: 14046
Either target NPC and auto attack or simply swipe at enemy. Watch the tooltip, the condition must be a <12 swing so if it fails this attempt then just respawn the enemy and retry.

Examples:
[![](https://i.imgur.com/WW2N1NHm.jpg)](https://i.imgur.com/WW2N1NH.png)
[![](https://i.imgur.com/0EH9htxm.jpg)](https://i.imgur.com/0EH9htx.png)

**Comment by mixxit** [comment]
The number at the bottom is the amount that is about to be changed to Vs the NPC's current hp at the time the message

**Comment by mixxit** [comment]
ill close this since the damage tip at the bottom of the screen are correct numbers
