### ISSUE TITLE
Zones Need Items Enabled to Allow Players to Spawn Purchased Horses

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#427]
Item use is disabled in all zones, so players cannot use the purchases spawn eggs to spawn their horses.

**Comment by mixxit** [comment]
this is the item use world guard region flag right?

**Comment by Ferreluke** [comment]
Yes, but I wasn't sure if enabling it would allow any unwanted things like buckets

**Comment by mixxit** [comment]
This should be fixed now
