### ISSUE TITLE
Chat Message Range - "No one hears you" Notification

### ISSUE THREAD

**Issue by Athorgo** [mixxit/solinia3-core#433]
In light of the local in character chat ranges being made shorter, can we get a little message whether in chat or in the sub text above our hot bar that tells us when no one hears us? 

We used to have this on the server a while ago where when you say or emote something out of range of any other player, then it says to you that no one hears you. I believe this will help with any confusion in RP that the ranges might cause when saying or doing something when just out of range.

**Comment by Ferreluke** [comment]
It may just be easier to extend local chat range. I'm not sure if checking for people hearing you and having the server respond would or wouldn't cause additional lag issues. Mixxit will have to weigh in on this, but extending local chat range would be a decent alternative if it isn't possible.

**Comment by Athorgo** [comment]
It's something we've have for a long time on the server before, and it's also common place in many RP servers as far as I know.

Though now that you mention it, if it is any significant load on the server, I'd imagine it would only be when players spam "HAIL" for whatever reason. Guess we'll see.

**Comment by Ferreluke** [comment]
I only worry because we've been having lag issues with mundane things lately. (like invisible armor stands that are produced by our sit plugin) I'm sure Mixxit will know if it's a viable option or not. It would be nice to have for sure.

**Comment by mixxit** [comment]
It's not removed because of lag

Players and NPC's all share the same emote chat and shout code to reduce duplication

I was in darnar and could hear local chat from an ezro npc so I lowered them to ranges that seemed appropriate for say

When an npc says something it's a fire and forget process so it might be difficult to know who heard you 

But I might be able to do the check before firing
