### ISSUE TITLE
Necomancer Spell Leech Not Working Properly

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#446]
The Necromancer Leech spell is supposed to drain health over time from an opponent (functioning as a DoT) and restore health to the caster over time. (functioning as a HoT) Currently, it appears to only drain health from the target but is not restoring health to the caster.

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/73610543-7401a380-45d0-11ea-8fdd-160ae769a024.png)

**Comment by mixxit** [comment]
there are many leech spells please confirm the one you want fixing

**Comment by Ferreluke** [comment]
Level 9 Necromancer spell: Leech https://everquest.allakhazam.com/db/spell.html?spell=1509

**Comment by mixxit** [comment]
Seems like the spell has a recourse spell id that should fire after the first spell

Im adding the field to editspell now so we can look

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/74151355-eb07ef00-4c03-11ea-8f3a-45f6a570eebd.png)

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/74151366-f529ed80-4c03-11ea-8a9d-dbabf3f23580.png)

**Comment by mixxit** [comment]
yep seems we can fire this back on success
