### ISSUE TITLE
Blunt Axe Non-Functional for Berserkers

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#447]
Blunt Axe is a reagent for many berserker abilities. Currently, it isn't be recognized as a reagent. Therefore, berserkers cannot add it to their reagent pouch and cannot use dependent abilities.

**Comment by mixxit** [comment]
this is already a reagent

![image](https://user-images.githubusercontent.com/233287/73610491-cdb59e00-45cf-11ea-996b-7c2460d49881.png)

**Comment by mixxit** [comment]
did someone make another one? 

![image](https://user-images.githubusercontent.com/233287/73610498-dad28d00-45cf-11ea-92ac-a4cee7a511f9.png)

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/73610517-1b320b00-45d0-11ea-809a-3bc54a77a725.png)

**Comment by mixxit** [comment]
fixed spell to point to the correct reagent
