### ISSUE TITLE
Berserker Corroded Axe No-Kill Issue

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#450]
Any creature killed by a berserker corroded axe doesn't drop items, award xp, or credit the kill to the player. I think it might be because the item base (player head) isn't recognized as a Solinia weapon. Maybe I'm wrong, but Khodhe and I tested it on different creatures, and no matter what, corroded axe kills yielded no xp and no item drops. (even on creatures with always true 100% drops)

**Comment by mixxit** [comment]
there was two of the coroded and blunt axe items
one to create the item and one to use the itme

set both to the one to use the item

**Comment by mixxit** [comment]
using right click (throw weapon) to attack doesnt trigger mob hatred
