### ISSUE TITLE
Mez does not interrupt spell casting

### ISSUE THREAD

**Issue by SilasWR** [mixxit/solinia3-core#456]
While mezzed, Players are still able to cast spells.

**Comment by mixxit** [comment]
The last patch was for this please confirm this is still an issue and reopen it if so

**Comment by mixxit** [comment]
Please do not combine two issues in one ticket x

**Comment by SilasWR** [comment]
> The last patch was for this please confirm this is still an issue and reopen it if so

Was requested to create a bug report in OOC chat when it was mentioned so it was done, though it was fixed anyhow. Noted for the future, Thanks!

**Comment by mixxit** [comment]
Reopening this as @SilasWR changed the subject

**Comment by SilasWR** [comment]
Confimed Mez interrupts spell casting now. Thanks for the hard work Mixxit!

**Comment by mixxit** [comment]
Please leave this open thanks

**Comment by mixxit** [comment]
```// Interupt casting
		try {
			CastingSpell castingSpell = StateManager.getInstance().getEntityManager().getCasting(getLivingEntity());
			if (castingSpell != null) {
				if (castingSpell.getSpell() != null && castingSpell.getSpell().getUninterruptable() == 0) {
					StateManager.getInstance().getEntityManager().interruptCasting(getLivingEntity());
				}
			}
		} catch (CoreStateInitException e) {

		}```
