### ISSUE TITLE
Mislabeled Spell: Translocate Tanqara

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#461]
The spell translocate Tanqara shows as a spell usable by the wrong classes. It looks like another spell was had its title accidentally edited by mistake.
![image](https://user-images.githubusercontent.com/36186683/74434316-d0ae5b00-4e27-11ea-8d6c-492737a1c4d5.png)

**Comment by mixxit** [comment]
This was Counteract Disease spell
