### ISSUE TITLE
Plugin not loading on server startup

### ISSUE THREAD

**Issue by SofieHL** [mixxit/solinia3-core#47]
When I start the server the plugin wont load with the following error:

https://pastebin.com/UAUjRpKJ

The error happens on both versions 1.12.1 and 1.12.2

The only plugins on the server are Solina3Core, LibsDisguises, Mythicmobs, Vault, and protocolLib.

**Comment by mixxit** [comment]
Add discord to your lib

**Comment by mixxit** [comment]
ie: 

spigot\lib\Discord4j-2.8.4-shaded.jar

**Comment by mixxit** [comment]
closing as this has been updated
