### ISSUE TITLE
Bard Mez Broken Again

### ISSUE THREAD

**Issue by PipkinPollywog** [mixxit/solinia3-core#472]
![image](https://user-images.githubusercontent.com/38431218/75402853-99ca5180-58cb-11ea-80bd-0ed9681682ce.png)

Used both Lucid lullaby and song of the sirens. Both give the message of: Your target cannot be affected (with this spell)

Attempted to cast these on more than one player of different classes just to make sure it was not a rouge thing. Enchanter mez is still working. This is only effecting bards

**Comment by mixxit** [comment]
That spell has a limit of level 25 so the target is immune to it

I have changed the error to explain a bit better
