### ISSUE TITLE
Track Not Functioning Properly

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#478]
Track has worked for both my druid and ranger, but at some point the tracking stops working. /track becomes non-functional at some point, though I do not know when or why. I was able to use it on a ranger and leveled 1 to 200 without stopping it. Then after starting again at skill 200 it no longer functions. My druid has rank 121 and also can no longer use /track.

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/76462033-e720e580-63d8-11ea-9848-33eb0c6d0cb2.png)

**Comment by mixxit** [comment]
hi mate, i cannot seem to get this to break, if you can show me when it happens though feel free to give me a shout
