### ISSUE TITLE
AC does not affect inbound damage

### ISSUE THREAD

**Issue by mikebollandajw** [mixxit/solinia3-core#479]
AC does not affect inbound damage (dern)

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/76462829-3c112b80-63da-11ea-9189-538d494c2cd0.png)

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/76463062-ad50de80-63da-11ea-8962-d7cfe0686fe4.png)

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/76463286-03258680-63db-11ea-87ab-0a93558837df.png)

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/76471672-3ec84c80-63eb-11ea-9aa3-a65520930501.png)

**Comment by mixxit** [comment]
Testing with Dev:

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/76476431-e64c7b80-63f9-11ea-8e4f-4cfafde9b4bb.png)

![image](https://user-images.githubusercontent.com/233287/76476437-eba9c600-63f9-11ea-940b-ed008a13184b.png)


Offense is incorrect, but AC is correct now

Need to adjust attack to solve d20 rolls to be more favourable to lower values in the meleeMitigation method

**Comment by Fran9676** [comment]
![2020-03-12_13 37 26](https://user-images.githubusercontent.com/40521706/76522450-e59dfe80-6466-11ea-9e54-1a07537314e8.png)
![2020-03-12_13 37 34](https://user-images.githubusercontent.com/40521706/76522462-ea62b280-6466-11ea-966b-2a076a6399db.png)
![2020-03-12_13 37 44](https://user-images.githubusercontent.com/40521706/76522471-ed5da300-6466-11ea-9fac-6ea82e852b51.png)
![2020-03-12_13 37 46](https://user-images.githubusercontent.com/40521706/76522481-f0589380-6466-11ea-8539-fe62d8264260.png)

**Comment by mixxit** [comment]
paladin:

![image](https://user-images.githubusercontent.com/233287/76522997-84266180-645f-11ea-82f7-a6e5a0e12e8e.png)

**Comment by mixxit** [comment]
fran:

**Comment by Fran9676** [comment]
![2020-03-12_13 55 46](https://user-images.githubusercontent.com/40521706/76523863-68c05400-6469-11ea-9041-4899bbc89296.png)

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/76524580-30694780-6462-11ea-90c7-dab7cb01c73a.png)

![image](https://user-images.githubusercontent.com/233287/76524592-352dfb80-6462-11ea-8cf7-bcbb37c63be8.png)
