### ISSUE TITLE
Character Switch Equals Death

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#483]
Upon using the character switch function the odds of character peril are quite high. I have tried to determine exactly what causes this to no avail. Risk factors include standing atop a single block thickness with space below said block while switching to a different character so that when switching back to the original character there is at least one open block somewhere below the character.

So very many times I have found myself in a cavern under the ground where I logged off. 

/stuck is great. One out of five times I use it. The rest of the time it does nothing and I die. Also /stuck is only usable every (i forget the number, but 4 or 5?) hours. And honestly /stuck has only actually helped me perhaps one in three times.

**Comment by mixxit** [comment]
i am having trouble replicating this, can you screenshot /getpos when you have the issue

**Comment by mixxit** [comment]
I have patched this, let me know how it goes mate
