### ISSUE TITLE
Enchanter Pet Attack Value broken

### ISSUE THREAD

**Issue by Lemondrop1999** [mixxit/solinia3-core#485]
It seems as though enchanter pets (potentially all pets, i haven't tested) have an attack value of 0, even with a weapon equipped. 
![image](https://user-images.githubusercontent.com/46408556/76722798-59a80300-6702-11ea-9535-49a53ad69729.png)
This is the info given after using /solnpcinfo on the pet (note the attack value left at 0)

**Comment by mixxit** [comment]
What is the spell name that pet has no race

**Comment by Lemondrop1999** [comment]
It's called Vaxils Animation. Though from what I have heard many pets seem to suffer this same issue with attack value (such as the necromancer spell Restless Bones)

**Comment by mixxit** [comment]
Can you show me the same screenshot for restless bones

**Comment by Lemondrop1999** [comment]
![image](https://user-images.githubusercontent.com/46408556/76742401-46ab2800-672e-11ea-877b-9c935f1b9e8b.png)

**Comment by mixxit** [comment]
Ok it's not race related then!
