### ISSUE TITLE
Wizard mastery spell isue

### ISSUE THREAD

**Issue by Ipponvader** [mixxit/solinia3-core#492]
Wizard Mastery doesn't give Rune on use, it does every other effect that is on the spell except from the rune. It also doesn't appears as a buff, just as a onetime damage and mana regen effect.
![2020-03-28_10 47 36](https://user-images.githubusercontent.com/55657983/77820314-9ea83e00-70e1-11ea-8655-492785e47ca2.png)

**Comment by mixxit** [comment]
this is not a valid spell, where did you find it?

**Comment by mixxit** [comment]
mistakenly added to vendor, removed thanks
