### ISSUE TITLE
Shamans Unable to Advance Slashing Skill

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#536]
Shamans don't advance slashing skill, despite using a slashing weapon. One-Eye was using one for over an hour, and the skill still doesn't advance or even appear on his list of skills. My ability to look view details and edit classes was removed with the recent permissions change.

**Comment by mixxit** [comment]
probably the skill code 

``` Weapons

Shamans can use most 1H and 2H blunt melee weapons in the game. These are generally effective weapons that are a little slower or weaker than slashing weapons are. They are also generally a bit heavier. Blunt weapons are still pretty effective overall, and there are a lot of high-quality magic ones out there. ```
