### ISSUE TITLE
Melee and Ranged Weapons Not Getting Crit Notifications

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#539]
Melee weapons and ranged weapons are getting critical hits, but the message displays just like a normal hit. It would be nice if the player received a notification to let them know their hit was a critical hit.

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/80273291-d7c7d400-86c8-11ea-8d6c-96d986d6e654.png)
