### ISSUE TITLE
Shield_Of_Enhancement

### ISSUE THREAD

**Issue by Jigglebox** [mixxit/solinia3-core#54]
The consumable effect's don't work on pets/user
https://gyazo.com/2ec72c02beb02aaa0e1c684631246700

**Comment by mixxit** [comment]
please try now?

**Comment by mixxit** [comment]
re-open if not fixed

**Comment by Jigglebox** [comment]
Can't tell if it buffed the stats, but the message shows up for having it buffed. Unsure if fixed or not. Waiting on more detailed /pet command to tell .

**Comment by mixxit** [comment]
ok, this is covered in ticket https://github.com/mixxit/solinia3-core/issues/53
