### ISSUE TITLE
Wizard Spell Minor Familiar Not Working

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#547]
Level 29 wizard spell minor familiar currently does nothing. It should summon a non-combat familiar (I suppose we could use a bat as the model) that grants 10 to all resists and increases effective casting level by 2.

**Comment by mixxit** [comment]
I started this a few days ago

https://github.com/mixxit/solinia3-core/commit/6e9c3ca731fc83db095b96b6bc1d2123229cba22

The pet itself is too hard right now, but you would still get the bonus once effective levels is implemented
