### ISSUE TITLE
Mentoring Bugs

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#551]
While mentoring down to level 21 and while in a group the higher level character did not gain any experience from the kills the group made. Also, higher level weapons show a message of being unusable until level 50 (when trying to use a level 50 weapon) rather than being able to use the higher level gear as I assume is intended. 

"You were out of level range to gain xp with this group. Min 14 Max 22.

**Comment by mixxit** [comment]
Resolved
