### ISSUE TITLE
Feature Request: Multiple Spellbars

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#554]
Per our discussion I would love to have multiple spellbars. As a shaman I have a spell book a quarter mile thick. Having two spellbars would be great. More is better.

Now with the implementation of mentoring I want additional spellbars even more. Honestly I think I could make good use out of 5 or more spellbars.

**Comment by DevistatorXL** [comment]
The restriction on the spell bar was purposeful, Though i had heard whispers among the winds of AA's that could increase spell slots.

**Comment by mixxit** [comment]
Could I meet you half way and give you spell load puts to quick load? I will add the additional spell slots for Aa latet

**Comment by mixxit** [comment]
Fixed
