### ISSUE TITLE
Slow fall racial + elytra

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#559]
When you play one of the races that gets slow fall wings and then you also use elytra the character glides at a shockingly slow rate. The rate of descent is almost completely negated, but your forward momentum is slower than a walk. I think I've seen every player complain about this since the racial was released. Is there a way to make elytra play nice with the slow fall racial?

**Comment by mixxit** [comment]
would it be ok to make the passive toggeleable?
