### ISSUE TITLE
Alchemy Skill Level

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#573]
One Eye had alchemy 180/180 yesterday. You added the AA that let me increase that by 50. I purchased it. I checked skills and was at 180/230. I logged on tonight after doing nothing else and now my skill is at 130/130.

**Comment by OdinGreybeard** [comment]
I don't know if it is related to my previous issues along these lines, but I wanted to note this is not the first time I have noticed the skill levels of alchemy changing suddenly and with no explanation that I could determine.

**Comment by mixxit** [comment]
this was related to a -1 base value causing a -50 bonus
