### ISSUE TITLE
Age and Time?

### ISSUE THREAD

**Issue by Athorgo** [mixxit/solinia3-core#59]
This one has nothing to do with plugins or anything, but I'm sure many people are curious as to how time goes by on the server in game. I feel like many people would appreciate something that doesn't move too fast to where it makes any given "year" a trivial year, but then again, not too long to where people intend to have a character age. There was one particular server that went with 2 weeks in real life was equal to a year in game, maybe that's a good starting point? It doesn't have to be any strict set of time, but just something to give people a ballpark estimate of how long they've been a member of a town for instance, or how much their character has aged since they started playing them.

**Comment by mixxit** [comment]
how would we know their age at the point of starting their character
