### ISSUE TITLE
Rogue AA not implemented

### ISSUE THREAD

**Issue by Fran9676** [mixxit/solinia3-core#600]
Escape AA isn't implemented, Dirty Fightning AA isn't implemented, Cunning Disguise: Erudite AA isn't implemented, Ligament Slice AA isn't implemented, Twisted Shank AA isn't implemented.

**Comment by Silternius** [comment]
All these AAs besides Escape (Cunning Disguise: Erudite, Dirty Fighting, Ligament Slice, Twisted Shank) are level 71 AAs

**Comment by Fran9676** [comment]
The spells say lvl 70, so it's an error of the lvl given xD

**Comment by Fran9676** [comment]
Escape AA is a lvl 59 aa
