### ISSUE TITLE
Killing Myconids isnt giving any Guardians of the Under faction alignment

### ISSUE THREAD

**Issue by Snip3rL0rd** [mixxit/solinia3-core#603]
When i kill Myconids it says that my Guardians of the Under faction alignment goes up, but it doesnt. 
![2020-05-21_13 40 21](https://user-images.githubusercontent.com/65265560/82594780-3cf8d300-9b6a-11ea-812f-48eea3a5cf81.png)
![2020-05-21_13 41 37](https://user-images.githubusercontent.com/65265560/82594786-3e2a0000-9b6a-11ea-9fb6-c463362db378.png)

**Comment by mixxit** [comment]
![image](https://user-images.githubusercontent.com/233287/82595009-d2ad5600-9b9c-11ea-8cda-b15e7be194e9.png)

cannot reproduce
