### ISSUE TITLE
Thoughts on Racial Passives

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#636]
Feedback post only:

I've heard from a couple of lidkim players that the breathing passive is quite underwhelming. So that has led me to consider other options you might consider for Undead. I love the idea of them having the same racial passive as their original body but imagine that would be hard to program. Perhaps improved resistance to stuns or fears? Improved armor class due to being dead? Some kind of self heal that represents them eating the flesh of a downed enemy (not drinking the blood like a mysmaal might). /shrug.

**Comment by mixxit** [comment]
ok sounds good! i will also fix lidkim

**Comment by mixxit** [comment]
hey i have given undead a spell for sustenanence can you tell me if its broken too op etc? closing for now
