### ISSUE TITLE
Veterans dont know what's bannable and what's not

### ISSUE THREAD

**Issue by Snip3rL0rd** [mixxit/solinia3-core#641]
There is not set rules or anything, so there's no way for a Veteran or other staff member to know when to ban somebody, Hacking is an obvious ban but there's other stuff such as player disrespect. I'm basically asking that you add a rules channel to the discord and possibly a rules board in game.

**Comment by mixxit** [comment]
if hate speach -> ban
if toxic -> ban
if hacking -> ban

**Comment by mixxit** [comment]
im going to remove toxic from this list as its subjective
