### ISSUE TITLE
You can make infinite money with blacksmithing

### ISSUE THREAD

**Issue by Snip3rL0rd** [mixxit/solinia3-core#649]
if you have max blacksmithing skill, you can make infinite money by creating ingots that cost 19 to make but sell for 22, so thats a $3 profit.

**Comment by mixxit** [comment]
how are you smelting? with coal or wood?

**Comment by Snip3rL0rd** [comment]
Im smelting with portable furnaces (its racial ingots)

**Comment by mixxit** [comment]
what item names?

**Comment by mixxit** [comment]
updated furnace price
