### ISSUE TITLE
Shadowknight spells non functional?

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#653]
A new player using technic modpack was unable to cast spells properly. I witnessed in the chat bar that the spell was being cast but apparently kept getting messages that the target wasn't valid no matter who was being targeted or what spell was cast.

**Comment by mixxit** [comment]
Non valid should give a reason as well

**Comment by mixxit** [comment]
```2019:~Vuldin_Bludice the Vipers Bane: "This is not a valid effect for the entity: Null"
2019:~Vuldin_Bludice the Vipers Bane: yes he's targetted.
```

**Comment by mixxit** [comment]
Copied user, issue doesnt occur

**Comment by mixxit** [comment]
Exception occuring in target selection checking, null is the message  of the exception, added stack trace next time it happens
