### ISSUE TITLE
lesser evacuate not working correctly 

### ISSUE THREAD

**Issue by captainagent96** [mixxit/solinia3-core#664]
I recently got the lesser evacuate spell, and tried it out when me and my brother were leveling, but it only tp'd me when it was supposed to tp the whole group. its not a big deal, but I thought id let you know

**Comment by mixxit** [comment]
how far were they?

**Comment by captainagent96** [comment]
um within …… fifteen blocks roughly the first time, but then we tried it again thinking it might be the distance and he was around three blocks away and it still didn't work

**Comment by mixxit** [comment]
just tested seems to be ok at the moment!
