### ISSUE TITLE
Major Server Side Lag

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#666]
The game is practically unplayable at the moment. Ailin and I are pretty sure it is server side. Consistent, not spikey lag.

**Comment by mixxit** [comment]
You got ticket 666 for this

![image](https://user-images.githubusercontent.com/233287/83956901-82035180-a85a-11ea-9221-7761ae466636.png)

**Comment by mixxit** [comment]
ive removed coreprotect and anti vpn since they were the highest

lemme know how it goes?
