### ISSUE TITLE
Warrior Area Taunt

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#668]
I have been trying to level the relevant skills for my warrior to reduce fizzling and improve combat effectiveness. I have been working on autocast for area taunt. I am wondering if area taunt should be tied to the Taunt Skill or if it should have its own. It fizzles enough to make me think it is intended to have its own skill.

**Comment by mixxit** [comment]
Is this the AA spell? If so I don't think it supposed to fizzle

**Comment by mixxit** [comment]
Spells with Skilltype None no longer fizzle
