### ISSUE TITLE
Very Low Priority: Bard Brass Instrument Issue

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#671]
I have been trying to level up the different instrument skills on my bard. Auto cast is helpful for that because as far as I can tell you don't level up the skill on the continued casting after your initial cast. It only levels up when you actually manually cast it. So auto cast is ideal for this. I have levelled up all but one of the skills quite successfully this way. Brass instruments does not appear to be working this way. I haven't gotten a single level up in the skill in an hour and a half of using one or the other of my brass instrument powers. One is called Dissension, the other Distruptive Discord.

**Comment by mixxit** [comment]
Had no target
