### ISSUE TITLE
Combat Update: Players Cannot Melee NPCs

### ISSUE THREAD

**Issue by OdinGreybeard** [mixxit/solinia3-core#690]
Spells still work fine. At first I just thought the attack animation didn't work, but turns out I just don't attack NPCs.

**Comment by mikebollanddp** [comment]
oh thats weird it tested that yesterday it just wasnt showing the animation

which npc?

**Comment by mixxit** [comment]
are you ok to show me this in game later? ive added animations to maybe help show

it wasnt your druid trying to use a weapon they dont have skill in was it?

**Comment by OdinGreybeard** [comment]
Just tested it longer. I was wrong. I should have tested it longer the last time. Turns out I just had a long series of missing and was fighting an NPC that is immune to stun, which automatically cuts out like a third of my orcish attacks.
