### ISSUE TITLE
Rogue Abilities

### ISSUE THREAD

**Issue by Ferreluke** [mixxit/solinia3-core#81]
Rogues could really use some love. A few of us have been leveling up rogues, and they currently have no working abilities. Sneak doesn't seem to work against mobs, and it certainly has no effect on players. Can't really hide from people when you're clearly still visible. lol Also, rogues could really use their class defining skills of backstab and applying poison to their weapons. Perhaps poison and backstab could be easily implemented as skills. Backstab might be a bit tricky, but I have faith in ya! Sorry that you're coming back to so many things, but your work and patience for us doesn't go without immense gratitude. Thanks for everything you do, Mixxit! <3

**Comment by mixxit** [comment]
Can you paste me a video of sneak not working on mobs

**Comment by mixxit** [comment]
Backstab implemented, closing as there was no video update regarding sneak which appears to be working
