### ISSUE TITLE
Bard spells opposite effect

### ISSUE THREAD

**Issue by joshuam158** [mixxit/solinia3-core#93]
huge bug on a few bard spells, as i just searched the EQ wiki as well to make sure i wasnt mistaken(edited)
joshuam158 - Today at 7:10 PM
Spells like 
- Chant_of_Flame
-Chant_of_Frost
-Chant_of_Poison
-Chant_Disease
-Curtailing_Chant
All do the wrong thing, they deal damage like expected BUT they are supposed to give resist(spelltype):-1/-38... 
Instead, all except curtailing_chant are giving +100 resistance to their respective type, where as Curtailing is set to 1, still giving a buff instead of a debuff
curtailing chant and chant of flame are also not implemented/not in loot tables but the others are

**Comment by joshuam158** [comment]
Also bard spell melliflous_motion, the bard shadowstep spell, needs to be fixed so it doesnt constantly cast sending you in a constant uncontrolable blink spree

**Comment by mixxit** [comment]
please retest this as i started using the buff formulas from eqemu

blink was always crappy on bard in eq
